### ISSUE TITLE
Manual interaction checklist has been completed by a human

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb-hub/terminusdb-live-pattern-library#40]
- [ ] Check to see that Data Product can be created
- [ ] Check ...

**Comment by spl** [comment]
* [ ] Check to see that a new user account can be created, logged in, and logged out.
* [ ] Check to see that a pre-existing user can log in and log out.
